### PR TITLE
Gulp

### PR DESCRIPTION
**Pull request by sboerrigter**
I have created a branche where I replaced Grunt with Gulp. This should fix issue #440, #389 and #463. 

## Gulp tasks
Gulp will run the following tasks:

* Compile Sass
* Create style.map files
* Compile CoffeeScript
* Lint Sass
* Lint CoffeeScript
* Lint PHP
* Watch Sass, CoffeeScript and PHP

Other stuff we might want to add:

* Lint only modified files (with `gulp-cached`)
* Lint HTML (see #470)
* Lint Twig (see #464)
* liveReload
* Uglify
* Concat
* Some kind of error notifier

## Compile Sass and CoffeeScript
The Sass and Coffeescript compiler works just like before with Grunt. Except it is a lot faster.

## Sass lint
I have used ‘gulp-scss-lint’ (https://www.npmjs.com/package/gulp-scss-lint) for lifting Sass. I have used the configurations on: http://sass-guidelin.es/#scss-lint. The config file is in the theme root. Is this the right place?

The Sass linter generates a lot of warnings at the moment. I think we should fix these before we merge this brace.

## CoffeeScript lint
I have used `gulp-coffeelint` (https://www.npmjs.com/package/gulp-coffeelint) for linting CoffeeScript. I don’t know which coding standards this linter uses. We might want to change this after we know what to do with #469.

## PHP lint
PHP code sniffer will report any code that doesn’t comply to the PSR2 coding standards directly in the gulp output.

I believe you do need to have 'PHPCS' installed on your system to make this work (installation instructions: https://github.com/squizlabs/PHP_CodeSniffer). Is there a way to add this dependency with NPM or can we assume that every developer has PHPCS installed?

I guess we won’t need the PHP linter we used with Grunt anymore since we use PHPCS now right?

## Before we merge this branche
I’ve merged the PSR branche into this branche to test the PHP codesniffer. So the PSR branche must be finished before we merge this branche to master.

## Testing
What do you guys think of this? Can anyone review my changes and test it?

### CODE REVIEW

**Comment by haroldangenent** [comment]
Thanks for your work. As stated in the other PR, this PR should _not_ attempt to fix #463 and probably #389 as well. This creates a larger scope than necessary and also causes potential merge problems.

**Comment by sboerrigter** [comment]
Ok sorry. I'll won't do it like this the next time.

What do you think of the Gulp implementation?

**Comment by haroldangenent** [comment]
Gulp seems cool and really fast! I also like it's messages better. You can find remarks on this PR and your comments. This branch is getting a bit (too) large for it's needs, so I hope I got everything.

Maybe we could keep this checklist up-to-date and edit this comment later on.

**Gulp**
- [ ] Better name for the task `default`. Why is the task called `default`?
- [ ] Some inconsistencies in `gulpfile.js`. What coding standards did you use for `gulpfile.js`?
- [ ] Remove "Hello" message. Sorry, it seems cool, but it just adds to the codebase and makes the file less readable.
- [ ] Bleep when there's an error (like in Grunt). Or is this expected behaviour?
- [ ] Put files to watch / compile in a variable (instead of declaring them twice)
- [ ] Why not `use strict` JS?

**CoffeeScript & Sass compilation**
- [ ] CoffeeScript still compiles, even if the linter fails
- [ ] CoffeeScript source maps don't exist
- [ ] CoffeeScript compiles different code than when using Grunt (doesn't wrap it in an anonymous function). Why?

**Sass compilation**
- [ ] Sass still compiles, even if the linter fails
- [ ] Sass source maps don't work. They get compiled in the wrong folder: `themes/trendpress/assets/styles/output/assets/styles/output/style.css.map`
- [ ] Sass source maps seem to change when I change something and revert it
- [ ] Sass compilation [seems different](https://github.com/trendwerk/trendpress/commit/325506de403e21c3d4350c8194c1ad33563afa04#diff-d4853563141724b30a5eb0d1fe796cfe). Why is that?
- [ ] TrendPress license seems different (GPLv3 is not supported anymore). Why is that? I don't even thing you can change it like that.
- [ ] I see you have made changes to `_variables.scss`, but the indentation still seems off and I'm not sure why the variables are aligned (this practice doesn't happen in any other files)

**Sass linter**
- [ ] We should remove the Sass linter and fix this in a different branch. Let's keep this branch specific for replacing Grunt by Gulp
- [ ] The linter settings should probably not be in the root of the theme

**CoffeeScript lint**
I agree, we should keep it the way we do things now and improve upon that later (so this branch can be merged as soon as possible).

**PHP Lint / PHP Code Sniffer**
- [ ] Stop linting / code sniffing files in the `vendor/` directory
- [ ] We still need the normal PHP lint to detect syntax errors (it's quite useful)
- [ ] The word 'lint' in the comment should be capitalized
- [ ] No error notification == not knowing something is not PSR-2 compliant
- [ ] PHP CS ignores `node_modules/` but doesn't ignore it when watching
- [ ] What are those `phpcs.phar` and `phpcbf.phar` files?

**Livereload**
- [ ] Doesn't seem to work for any task. Does this need additional setup?

**Watch**
- [ ] Rename the "Watch things" comment to "Watch"

**Future stuff**
Could you create separate issues for future ideas? And update your list? (LiveReload seems to be implemented partially)

**Fixing this PR and branch**
- [ ] I still believe this PR should be fixed before it can be merged to master. Merging the `psr` branch will probably cause conflicts because this branch tries to do too much. What do you propose to fix it? We could:
 - Remove the commits
 - Re-do the branch without `psr`
 - Revert the branch to a previous version and add changes upon it
- [ ] The entire commit named "Apply coding standards" does not seems to belong in this branch and will cause conflicts. Sometimes I don't get the adjustments made (removed indentations where one should be in Twig files)

**Comment by sboerrigter** [comment]
Thanks for reviewing my PR. I have checked the fixed issues in your list above. You'll find my reaction to some of your feeback below.

I suggest we merge this branche and create separate issues for the remaining feedback, so we can discuss them separately. Does everybody agree?

--

**Better name for the task default. Why is the task called default?**
Default is an obligatory task which is run when you type the gulp command. Without this task Gulp doesn't work, so we can't change this.

**Some inconsistencies in gulpfile.js. What coding standards did you use for gulpfile.js?**
I removed the inconsistencies I could find. I didn't use any coding standards.

**Remove "Hello" message. Sorry, it seems cool, but it just adds to the codebase and makes the file less readable.**
@luukdv says: no!

**Bleep when there's an error (like in Grunt). Or is this expected behaviour?**
This is on the list with stuff we could add later. Let's focus on the basics first.

**CoffeeScript still compiles, even if the linter fails**
Not here. I can't reproduce this issue.

**CoffeeScript source maps don't exist**
I don't thinks that's necessary for only two files.

**CoffeeScript compiles different code than when using Grunt (doesn't wrap it in an anonymous function). Why?**
Not sure. Is this a problem? What does this anonymous function wrapper do?

**Sass still compiles, even if the linter fails**
Yes, I think we still would want the sass to compile if we just made a small code style error. We can then make the code work first and fix the styling issues later. Don't you agree?

**Sass compilation seems different. Why is that?**
We now use gulp-sass. What's wrong with it?

**TrendPress license seems different (GPLv3 is not supported anymore). Why is that? I don't even think you can change it like that.**
In what file? I only see GPLv2

**No error notification == not knowing something is not PSR-2 compliant**
I don't understand what you mean.

**What are those phpcs.phar and phpcbf.phar files?**
Where do you see these files?

**Livereload doesn't seem to work for any task. Does this need additional setup?**
Jep. You need this browser plugin: https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

**Fixing this PR and branch**
I just merged the master brance into and replaced Grunt with Gulp. I won't change anything else.

**Comment by sboerrigter** [comment]
I've also just added PHP lint, but it probably lucks

**Comment by sboerrigter** [comment]
@gewoonderrik and @luukdv can you guys please give me some feedback on this post: https://github.com/trendwerk/trendpress/pull/471#issuecomment-125948020

**Comment by gewoonderrik** [comment]
Some feedback on my behalve:

* **Better name for the task default. Why is the task called default?** - Grunt has a default task as well. So I guess this is sort of an industry standard?
* **Remove "Hello" message. Sorry, it seems cool, but it just adds to the codebase and makes the file less readable.** - I like it too. A bit of humour / office culture. Nothing wrong with that.
* **Bleep when there's an error (like in Grunt). Or is this expected behaviour?** - Agreed. It isn't necessary to add this right away.
* **CoffeeScript source maps don't exist** - This is a must have feature as far as I'm concerned. And it's probably quite easy to add. Right?
* **Sass still compiles, even if the linter fails** - I'm working on fixing these errors at the moment. More on that later.

**Comment by haroldangenent** [comment]
Thanks again.

*Discussion*

**Some inconsistencies in gulpfile.js. What coding standards did you use for gulpfile.js?**
This still seems off, for example:

```
gulp.task('sass', function() {
```

```
gulp.task('coffeelint', function () {
```
_Has a space after the keyword `function`_.

```
gulp.task('default',function() {
```
_Has no space before `function` keyword._

There are several other inconsistenties. For example, in the comments some words are capitalized and others are not.

**"Hello" message.**
If you all think so we should keep it. But the code could be a bit more compact (and maybe tucked away, so the file is still readable).

**Bleep**
Okay.

**CoffeeScript still compiles, even if the linter fails**
So whenever you write CoffeeScript that is not linted correctly, the file does not get compiled? That would actually be strange behaviour when looking at the code.. Please try and reproduce again, because I'm quite sure this is still an issue.

**CoffeeScript source maps don't exist**
I do think it's necessary, because the number of lines per file is different. It's not a matter of more or less files. This is also how things worked with Grunt.

Also, the files exist but are not updated: https://github.com/trendwerk/trendpress/tree/gulp/assets/scripts/output.

**CoffeeScript compiles different code than when using Grunt (doesn't wrap it in an anonymous function).**
It's probably a good idea to wrap them. [Here's one of the reasons](http://stackoverflow.com/questions/1639180/how-does-the-function-construct-work-and-why-do-people-use-it). It's also a good idea to know why Gulp compiles differenly than Grunt, maybe there's a setting off.

**Sass still compiles, even if the linter fails**
I don't agree. Without any notifications, you don't even notice that the code is not written by coding standards. I think it would be better to write good code immediately. The best way to notice it is to make it not work.

**Sass compilation seems different. Why is that? _We now use gulp-sass. What's wrong with it?_**
I don't know if something is wrong with it. Just wondering why it doesn't compile the same.

**GPL License**
You've changed it here: https://github.com/trendwerk/trendpress/commit/325506de403e21c3d4350c8194c1ad33563afa04#diff-da232d78aa810382f2dcdceae308ff8eL12 but it seems to be reversed again.

**No error notification == not knowing something is not PSR-2 compliant**
Without any notifications, you never get notified that your code is not PSR-2 compliant (since it still works).

**What are those phpcs.phar and phpcbf.phar files?**
Last two files: https://github.com/trendwerk/trendpress/commit/8f2de42c87696600faf03618a678ef2522124d14

**LiveReload**
It seems to reload an excessive amount. If I change 1 PHP file, it reloads like 14 times.

*Merge*
There are still merge conflicts somehow.

*Status*
I'll post an updated list of the status of this PR below.

**Comment by haroldangenent** [comment]
Updated list, added a few things as well:

**Gulp**
- [ ] Some inconsistencies in `gulpfile.js`. Maybe use some coding standards.
- [ ] Trim "Hello" message and maybe tuck it away a bit (so `gruntfile.js` is more readable)
- [ ] Put files to watch / compile in a variable (instead of declaring them twice or thrice)
- [ ] Why not `use strict` JS?
- [x] ~~Better name for the task `default`. Why is the task called `default`?~~
- [x] ~~Remove "Hello" message. Sorry, it seems cool, but it just adds to the codebase and makes the file less readable.~~
- [x] ~~Bleep when there's an error (like in Grunt). Or is this expected behaviour?~~

**CoffeeScript & Sass compilation**
- [ ] CoffeeScript source maps don't exist
- [ ] CoffeeScript still compiles, even if the linter fails
- [x] CoffeeScript compiles different code than when using Grunt (doesn't wrap it in an anonymous function). Why?

**Sass compilation**
- [ ] Sass still compiles, even if the linter fails
- [ ] Sass source maps seem to change when I change something and revert it
- [ ] Sass compilation [seems different](https://github.com/trendwerk/trendpress/commit/325506de403e21c3d4350c8194c1ad33563afa04#diff-d4853563141724b30a5eb0d1fe796cfe). Why is that?
- [x] Sass source maps don't work. They get compiled in the wrong folder: `themes/trendpress/assets/styles/output/assets/styles/output/style.css.map`
- [x] TrendPress license seems different (GPLv3 is not supported anymore). Why is that? I don't even think you can change it like that.
- [x] I see you have made changes to `_variables.scss`, but the indentation still seems off and I'm not sure why the variables are aligned (this practice doesn't happen in any other files)

**Sass linter**
- [x] We should remove the Sass linter and fix this in a different branch. Let's keep this branch specific for replacing Grunt by Gulp
- [x] The linter settings should probably not be in the root of the theme

**PHP Lint / PHP Code Sniffer**
- [ ] PHP Lint
- [ ] No error notification == not knowing something is not PSR-2 compliant
- [ ] What are those `phpcs.phar` and `phpcbf.phar` files?
- [x] Stop linting / code sniffing files in the `vendor/` directory
- [x] We still need the normal PHP lint to detect syntax errors (it's quite useful)
- [x] The word 'lint' in the comment should be capitalized
- [x] PHP CS ignores `node_modules/` but doesn't ignore it when watching

**Livereload**
- [ ] Livereload works for some tasks. Why not all tasks?
- [ ] Livereload seems to reload an excessive amount
- [x] Doesn't seem to work for any task. Does this need additional setup?

**Watch**
- [x] Rename the "Watch things" comment to "Watch"

**Fixing this PR and branch**
- [x] I still believe this PR should be fixed before it can be merged to master. Merging the `psr` branch will probably cause conflicts because this branch tries to do too much. What do you propose to fix it? We could:
 - Remove the commits
 - Re-do the branch without `psr`
 - Revert the branch to a previous version and add changes upon it
- [x] The entire commit named "Apply coding standards" does not seems to belong in this branch and will cause conflicts. Sometimes I don't get the adjustments made (removed indentations where one should be in Twig files)

**Comment by haroldangenent** [comment]
@sboerrigter Worked on this feature. Changed a few things and fixed the rest of the issues. See commits for full report.

Could you merge this? I noticed some conflicts.

**Pull request merged**
