### PR TITLE
PSR-2 compatibility

### LINKED ISSUE #462: PSR Compatibility
We're currently using WP Coding Standards. This issue proposes to use PSR. We should implement:

- `PSR-4`: autoloading
- `PSR-1`: basic coding standards
- `PSR-2`: coding style guide

### LINKED ISSUE #463: PHP-CS
As soon as #462 is completed, we should test and implement the PHP Coding Standards Fixer: https://www.npmjs.com/package/grunt-php-cs-fixer.

### LINKED ISSUE #467: Remove pagination function in favor of a Timber helper

### PR DESCRIPTION
**Pull request by haroldangenent**
This pull request is not finished yet. 

It attempts to fix #463 and also fixes #462.

### CODE REVIEW

**Comment by sboerrigter** [comment]
I've tested this with PHP codesniffer. Looks good! It only gives errors on your Autoloader file. I have fixed this in https://github.com/trendwerk/trendpress/pull/471.

**Comment by haroldangenent** [comment]
Thanks. Since I am still working on this, merging the unfinished branch to another one was a bad idea, especially editing this code in that branch which was unrelated.

I have already fixed, researched and added a few practices in the `psr` branch (and this PR), which is dedicated to PSR. You should probably fix the `gulp` PR to not include this one, or keep it updated until finished.

**Comment by haroldangenent** [comment]
This branch is ready for testing. Decided not to fix #467 immediately, since it was not an absolute necessity.

Please review.

**Comment by luukdv** [comment]
Looks ready for merging.

**Pull request merged**
